name: bicep_totest.yml

on: [workflow_dispatch]

env:
  baselineResourceGroup: ghgovenv
  baselineVariableStorageAccountName: ghgovenvnotsecrets
  baselineVariableTableName: pipelinevariables
  baselineTablePartitionKey: totestvariables
  
jobs:
  buildbicepappserviceplpan:
    runs-on: ubuntu-latest
    
  
    
    
  
