name: bicep_totest.yml

on: [workflow_dispatch]

env:
  baselineResourceGroup: ghgovenv
  baselineVariableStorageAccountName: ghgovenvnotsecrets
  baselineVariableTableName: pipelinevariables
  baselineTablePartitionKey: totestvariables
  
jobs:
  buildbicepappserviceplpan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.3.4
  
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: ver
      run: ls
        
    - name: Deploy App Service Plan to Azure
      run: az deployment group create -g bicep --template-file ../bicep/appserviceplan.bicep --parameters aspName=asp-biceptestaspps27res
    
  
    
    
  
