name: bicep_totest.yml

on: [workflow_dispatch]

env:
  baselineResourceGroup: ghgovenv
  baselineVariableStorageAccountName: ghgovenvnotsecrets
  baselineVariableTableName: pipelinevariables
  baselineTablePartitionKey: totestvariables
  
jobs:
  buildbicepappserviceplpan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Deploy App Service Plan to Azure
      working-directory: ./bicep
      run: az deployment group create -g bicep --template-file .\appserviceplan.bicep --parameters aspName=asp-biceptestaspps27res
    
  
    
    
  
