name: gu_deploytopreprod

on: 
  workflow_dispatch:
  repository_dispatch:
    types: preprod

env:
  baselineResourceGroup: ghgovenv
  baselineVariableStorageAccountName: ghgovenvnotsecrets
  baselineVariableTableName: pipelinevariables
  baselineTablePartitionKey: topreprodvariables

jobs:
  buildanddeploy:

    runs-on: ubuntu-latest
    environment: govdemo

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Install dependencies
      run: dotnet restore "Code To Push To Environments/App Service Web App/DevAppSample.sln"
      
    - name: Build
      run: |
       dotnet build --configuration Release --no-restore "Code To Push To Environments/App Service Web App/DevAppSample.sln"
       dotnet publish --configuration Release -o "./releaseoutput" "Code To Push To Environments/App Service Web App/DevAppSample.sln"
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Get Primary Storage Key
      run: echo "STORAGE_KEY=$(az storage account keys list -g $baselineResourceGroup -n $baselineVariableStorageAccountName --query "[0].{value:value}" -o tsv)" >> $GITHUB_ENV 
         
    - name: Set Storage Connection String
      run: echo "CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=$baselineVariableStorageAccountName;AccountKey=$STORAGE_KEY;EndpointSuffix=core.windows.net" >> $GITHUB_ENV 
      
    - name: Get App Service Name
      run: echo "APPSERVICENAME=$(az storage entity show --connection-string $CONNECTION_STRING --table-name $baselineVariableTableName --partition-key $baselineTablePartitionKey --row-key appservicename --select Content --query "Content" -o tsv)" >> $GITHUB_ENV
      
    - name: Show Pipeline Variables
      run: | 
        echo "Partition key:" $baselineTablePartitionKey
        echo "App Service Name:" $APPSERVICENAME
    - name: 'Run Azure webapp deploy action'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{env.APPSERVICENAME}}
        package: "./releaseoutput"
               
    - name: Dispatch to run prod workflow
      if: success()
      run: |
        curl -X POST https://api.github.com/repos/onemtc/governance-script-sandbox/dispatches \
            -H 'Accept: application/vnd.github.v3+json' \
            -H 'Authorization: token ${{ secrets.REPO_DISPATCH }}' \
            -d '{"event_type": "prod"}'
